# Generated by Django 4.1.7 on 2023-03-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="REmployeeType", new_name="EmployeeType",),
        migrations.AddField(
            model_name="guest",
            name="last_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Booking_Guest",
                to="room_reservation.guest",
            ),
        ),
    ]
