# Generated by Django 4.1.7 on 2023-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0003_remove_booking_booking_room_booking_rooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="employeetype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="room", name="room_no", field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
