# Generated by Django 4.1.7 on 2023-03-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room_reservation", "0004_alter_agent_name_alter_employeetype_name_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="agent", table="tbl_rez_agent",),
        migrations.AlterModelTable(name="guest", table="tbl_rez_guest",),
    ]
